services:
  - type: web
    name: jagy-automation-engine
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    envVars:
      - key: PORT
        value: 8000
