import os
import time
import yaml
import logging
from typing import List, Dict, Optional
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from googleapiclient.errors import HttpError

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

SCOPES = ['https://www.googleapis.com/auth/youtube.upload',
          'https://www.googleapis.com/auth/youtube.force-ssl',
          'https://www.googleapis.com/auth/youtube.readonly']

class YouTubeUploader:
    def __init__(self, config_path: str = 'config/config.yaml'):
        self.config_path = config_path
        self._load_config()
        self.youtube = None

    def _load_config(self):
        try:
            with open(self.config_path, 'r') as f:
                self.config = yaml.safe_load(f)
        except Exception as e:
            logger.error(f"Failed to load config from {self.config_path}: {e}")
            self.config = {}

    def authenticate(self, interactive: bool = False) -> bool:
        """Load/refresh OAuth token, return True if successful."""
        client_secrets_file = self.config.get('platforms', {}).get('youtube', {}).get('client_secrets', 'client_secrets.json')
        token_file = self.config.get('platforms', {}).get('youtube', {}).get('token_file', 'token.json')
        
        creds = None
        if os.path.exists(token_file):
            try:
                creds = Credentials.from_authorized_user_file(token_file, SCOPES)
            except Exception as e:
                logger.warning(f"Could not read token file {token_file}: {e}")
                creds = None
            
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                try:
                    creds.refresh(Request())
                except Exception as e:
                    logger.error(f"Failed to refresh token: {e}")
                    creds = None
                    
            if not creds:
                if not interactive:
                    logger.error(
                        f"YouTube OAuth token in '{token_file}' is expired or revoked and cannot be refreshed automatically in background mode.\n"
                        f"ACTION REQUIRED: Double-click 'reauth_youtube.bat' to authorize your YouTube channel via browser."
                    )
                    return False
                if not os.path.exists(client_secrets_file):
                    logger.error(f"Client secrets file {client_secrets_file} not found.")
                    return False
                flow = InstalledAppFlow.from_client_secrets_file(client_secrets_file, SCOPES)
                creds = flow.run_local_server(port=0)
                
            try:
                with open(token_file, 'w') as token:
                    token.write(creds.to_json())
            except Exception as e:
                logger.error(f"Failed to save token to {token_file}: {e}")
                
        try:
            self.youtube = build('youtube', 'v3', credentials=creds)
            logger.info("Successfully authenticated with YouTube API.")
            return True
        except Exception as e:
            logger.error(f"Failed to build YouTube service: {e}")
            return False

    def upload_short(self, video_path: str, title: str, description: str, tags: List[str], category_id: str = '27') -> Optional[str]:
        """Upload video as Short, return video_id."""
        if not self.youtube:
            if not self.authenticate():
                return None

        if '#Shorts' not in title:
            title += " #Shorts"
            
        # Add AI disclosure if required by policy (mock logic)
        description += "\n\n[Disclosure: This content was partially generated by AI.]"

        body = {
            'snippet': {
                'title': title,
                'description': description,
                'tags': tags,
                'categoryId': category_id
            },
            'status': {
                'privacyStatus': 'public',
                'selfDeclaredMadeForKids': False
            }
        }

        media = MediaFileUpload(video_path, chunksize=1024*1024*2, resumable=True)

        try:
            request = self.youtube.videos().insert(
                part=','.join(body.keys()),
                body=body,
                media_body=media
            )
            
            response = None
            while response is None:
                status, response = request.next_chunk()
                if status:
                    logger.info(f"Upload progress: {int(status.progress() * 100)}%")
                    
            logger.info(f"Video uploaded successfully. Video ID: {response['id']}")
            return response['id']
            
        except HttpError as e:
            logger.error(f"An HTTP error {e.resp.status} occurred: {e.content}")
            return None

    def get_video_stats(self, video_id: str) -> Dict:
        """Get view count, likes, comments for a video."""
        if not self.youtube:
            return {}
            
        try:
            request = self.youtube.videos().list(
                part="statistics",
                id=video_id
            )
            response = request.execute()
            if response['items']:
                return response['items'][0]['statistics']
            return {}
        except Exception as e:
            logger.error(f"Failed to get video stats: {e}")
            return {}

    def post_comment(self, video_id: str, text: str) -> Optional[str]:
        """Post comment on video, return comment_id."""
        if not self.youtube:
            return None
            
        try:
            request = self.youtube.commentThreads().insert(
                part="snippet",
                body={
                    "snippet": {
                        "videoId": video_id,
                        "topLevelComment": {
                            "snippet": {
                                "textOriginal": text
                            }
                        }
                    }
                }
            )
            response = request.execute()
            return response['id']
        except Exception as e:
            logger.error(f"Failed to post comment: {e}")
            return None

    def pin_comment(self, comment_id: str):
        """Pin a comment (not directly supported, log an action)."""
        # The YouTube Data API v3 does not officially support pinning comments.
        logger.warning(f"Pinning comment {comment_id} is not directly supported by YouTube Data API v3.")

    def heart_comment(self, comment_id: str):
        """Heart/like a comment (not directly supported, log an action)."""
        # The YouTube Data API v3 does not officially support hearting comments.
        logger.warning(f"Hearting comment {comment_id} is not directly supported by YouTube Data API v3.")

    def get_recent_comments(self, video_id: str, max_results: int = 20) -> List[Dict]:
        """Get recent comments on a video."""
        if not self.youtube:
            return []
            
        try:
            request = self.youtube.commentThreads().list(
                part="snippet",
                videoId=video_id,
                maxResults=max_results,
                order="time"
            )
            response = request.execute()
            return response.get('items', [])
        except Exception as e:
            logger.error(f"Failed to get recent comments: {e}")
            return []

    def reply_to_comment(self, parent_comment_id: str, text: str) -> Optional[str]:
        """Reply to a comment."""
        if not self.youtube:
            return None
            
        try:
            request = self.youtube.comments().insert(
                part="snippet",
                body={
                    "snippet": {
                        "parentId": parent_comment_id,
                        "textOriginal": text
                    }
                }
            )
            response = request.execute()
            return response['id']
        except Exception as e:
            logger.error(f"Failed to reply to comment: {e}")
            return None

if __name__ == "__main__":
    uploader = YouTubeUploader()
    # To test locally, ensure config.yaml and client_secrets.json are set up
    # uploader.authenticate()
    # video_id = uploader.upload_short("test.mp4", "Test Short", "This is a test #Shorts", ["test", "shorts"])
    # if video_id:
    #     print(uploader.get_video_stats(video_id))
